name: Build workspace

on:
  push:
    branches: [master]
    paths-ignore: 
      - README.md
      - doc/

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v7
      
    - name: Run a multi-line script
      run: |
        cd machines/workspace
        nix-build '<nixpkgs/nixos>' -A config.system.build.virtualBoxOVA -I nixos-config=configure.nix
        mv result/*-linux.ova result/linux.ova

    - uses: actions/upload-artifact@v1
      with:
        name: image
        path: machines/workspace/result/linux.ova
