name: Certs

on:
  workflow_dispatch:

  schedule:
    - cron: '0 0 * * *'
    

concurrency: cert

jobs:
  prometheus:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: UM-LPM/known_hosts
          path: known_hosts
      - name: Set known hosts
        run: install -D -m 600 known_hosts/known_hosts ~/.ssh/known_hosts
      
      - name: Generate
        working-directory: ./certs
        run: ./genprometheus.sh
      
      - name: Deploy
        run: |
          copy() {
            local og=$1
            shift
            local mod=$1
            shift
            rsync -e 'ssh -F ./machines/ssh_config' -og --chown="$og" --perms --chmod="$mod" "$@"
          }
        
          eval "$(ssh-agent)"
          ssh-add - <<< "${{secrets.sshkey}}"
          copy "prometheus:prometheus" 600 ./certs/prometheus.key prometheus:/etc/ssl/private/
          copy "prometheus:prometheus" 644 ./certs/prometheus.crt prometheus:/etc/ssl/certs/
          copy "node-exporter:node-exporter" 644 ./certs/prometheus.crt green:/etc/ssl/certs/
