name: Deploy

on:
  push:
    branches: [ master ]
    paths-ignore:
      - README.md
      - doc/**

concurrency: deploy

jobs:
  bastion:
    uses: UM-LPM/server/.github/workflows/deploy-machine.yml@master
    with:
      machine: bastion
    secrets: inherit

  machines:
    strategy:
      matrix:
        machine: [green, gateway.l, builder.l, calendar.l, prometheus.l, proxy.l, sso-test.l, spum-platform, grades, ps, esp, usatour, bioma, gb, ears, collab]

    needs: bastion

    uses: UM-LPM/server/.github/workflows/deploy-machine.yml@master
    with:
      machine: ${{matrix.machine}}
    secrets: inherit



