name: Deploy

on:
  push:
    branches: [ master ]
    paths-ignore:
      - README.md
      - doc/**

concurrency: deploy

jobs:
  #infra:
  #  uses: UM-LPM/server/.github/workflows/deploy-infra.yml@master
  #  secrets: inherit
    
  bastion:
    uses: UM-LPM/server/.github/workflows/deploy-machine.yml@master
    with:
      machine: "bastion.l"
    secrets: inherit
    
   # needs: infra

  machines:
    strategy:
      matrix:
        machine: ["gateway.l", "collab.l", "collab-dev.l"]

    needs: bastion

    uses: UM-LPM/server/.github/workflows/deploy-machine.yml@master
    with:
      machine: ${{matrix.machine}}
    secrets: inherit



