name: Deploy

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Update, Update courses]
    types:
      - completed
  push:
    branches: [ master ]
    paths-ignore:
      - README.md
      - doc/**

concurrency: deploy

jobs:
  #infra:
  #  uses: UM-LPM/server/.github/workflows/deploy-infra.yml@master
  #  secrets: inherit

  bastion:
    uses: UM-LPM/server/.github/workflows/deploy-machine.yml@master
    with:
      machine: "bastion.l"
    secrets: inherit

   # needs: infra

  machines:
    strategy:
      matrix:
        machine:
          - "minimal.l"
          - "gateway.l"
          - "builder.l"
          - "runner1.l"
          - "proxy.l"
          - "collab.l"
          - "collab-dev.l"
          - "collab-test.l"
          - "collab-pora.l"
          - "collab-rri.l"
          - "collab-vr.l"
          - "collab-rsasm.l"
          - "collab-catalog-dev.l"
          - "login.l"
          - "login-dev.l"
          - "gc.l"
          - "gc-dev.l"
          - "catalog.l"
          - "catalog-dev.l"
          - "catalog-view.l"
          - "catalog-manage.l"
          - "catalog-summer-schools.l"
          - "catalog-mini-academy.l"
          - "grades.l"
          - "grades-dev.l"
          - "student-mqtt.l"
          - "bioma.l"
          - "ps.l"
          - "feriusa.l"
          - "usatour.l"
          - "ears.l"
          - "prometheus.l"
          - "school-project.l"
      fail-fast: false
    needs: bastion

    uses: UM-LPM/server/.github/workflows/deploy-machine.yml@master
    with:
      machine: ${{matrix.machine}}
    secrets: inherit



