name: Deploy machine

on:
  workflow_call:
    inputs:
      machine:
        required: true
        type: string
    secrets:
      sshkey:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
      with:
        repository: UM-LPM/known_hosts
        path: known_hosts
    - uses: cachix/install-nix-action@v18
      with: 
        nix_path: nixpkgs=channel:nixos-22.05

    - name: Set known hosts
      run: install -D -m 600 known_hosts/known_hosts ~/.ssh/known_hosts
    
    - name: Deploy
      run: |
        eval "$(ssh-agent)"
        ssh-add - <<< "${{secrets.sshkey}}"
        cd machines
        ./deploy.sh ${{inputs.machine}}

