name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths-ignore:
      - README.md
      - doc/**

concurrency: deploy

jobs:
  #infra:
  #  uses: UM-LPM/server/.github/workflows/deploy-infra.yml@master
  #  secrets: inherit
    
  bastion:
    uses: UM-LPM/server/.github/workflows/deploy-machine.yml@master
    with:
      machine: "bastion.l"
    secrets: inherit
    
   # needs: infra

  machines:
    strategy:
      matrix:
        machine: ["minimal.l", "collab.l", "collab-dev.l", "builder.l", "prometheus.l", "runner1.l", "login.l", "gc.l", "proxy.l", "pmd-catalog.l", "student-mqtt.l", "bioma.l", "ps.l"]

    needs: bastion

    uses: UM-LPM/server/.github/workflows/deploy-machine.yml@master
    with:
      machine: ${{matrix.machine}}
    secrets: inherit



