name: Deploy

on:
  push:
    branches: [ master ]
    paths-ignore:
      - README.md
      - doc/

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
        repository: UM-LPM/known_hosts
        path: known_hosts
    - uses: cachix/install-nix-action@v7

    - name: Set known hosts
      run: mkdir -p ~/.ssh && cp known_hosts/known_hosts ~/.ssh/known_hosts
    
    - name: Deploy
      run: |
        eval "$(ssh-agent)"
        ssh-add - <<< "${{secrets.sshkey}}"
        cd machines
        ./deploy.sh
