name: Deploy machine

on:
  workflow_call:
    inputs:
      machine:
        required: true
        type: string
    secrets:
      sshkey:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        github_access_token: ${{secrets.GITHUB_TOKEN}}
        extra_nix_config: |
          access-tokens = github.com=${{secrets.PAT}}
          extra-substituters = https://cache.lpm.feri.um.si?priority=100
          extra-trusted-public-keys = cache.lpm.feri.um.si:TwiF0KOXmbNihiysjGaH7EZOMHUvuwy+1mI/EHGc56M=
          trusted-substituters = https://cache.lpm.feri.um.si

    - name: Deploy
      run: |
        build() {
          nix build --no-link "$@"
          nix path-info "$@"
        }
        install -D -m 400 $(build '.#known-hosts') ~/.ssh/known_hosts

        eval "$(ssh-agent)"
        ssh-add - <<< "${{secrets.sshkey}}"

        nix path-info -r /nix/store/fz59zs6awmm3xflkfvwpg7546y7pyjz8-mongodb-4.4.25 --store https://cache.lpm.feri.um.si
        
        ./deploy.sh ${{inputs.machine}}



