name: Deploy machine

on:
  workflow_call:
    inputs:
      machine:
        required: true
        type: string
    secrets:
      sshkey:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        github_access_token: ${{secrets.GITHUB_TOKEN}}
        extra_nix_config: |
          access-tokens = github.com=${{secrets.PAT}}
          extra-substituters = https://cache.lpm.feri.um.si
          extra-trusted-public-keys = cache.lpm.feri.um.si:mRrqApyiZICyeWfyiEoJPy+Cz50YAJhN9Gpe49Bhmos=
          trusted-substituters = https://cache.lpm.feri.um.si

    - name: Deploy
      run: |
        build() {
          nix build --no-link "$@"
          nix path-info "$@"
        }
        install -D -m 400 $(build '.#known-hosts') ~/.ssh/known_hosts
        
        eval "$(ssh-agent)"
        ssh-add - <<< "${{secrets.sshkey}}"
        nix flake update
        ./deploy.sh ${{inputs.machine}}



