name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
        repository: UM-LPM/known_hosts 
        path: machines
    - uses: cachix/install-nix-action@v7

    # Runs a single command using the runners shell
    - name: Deploy
      run: |
        eval "$(ssh-agent)"
        ssh-add - <<< "${{secrets.sshkey}}"
        cd machines
        ./deploy.sh
