name: Deploy

on:
  push:
    branches: [ master ]
    paths-ignore:
      - README.md
      - doc/

concurrency: deploy

jobs:
  bastion:
    uses: UM-LPM/server/.github/workflows/deploy-machine.yml@main
    with:
      machine: bastion
      sshkey: ${{secrets.sshkey}}

  machines:
    strategy:
      matrix:
        machine: [gateway, spum-platform, builder, grades, ps, esp, usatour, calendar, prometheus, bioma, gb, ears, collab]

    needs: bastion

    uses: UM-LPM/server/.github/workflows/deploy-machine.yml@master
    with:
      machine: ${{matrix.machine}}
      secrets: inherit



