name: Deploy infra

on:
  workflow_call:
    secrets:
      serversshkey:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
      with:
        repository: UM-LPM/known_hosts
        path: known_hosts
    - uses: cachix/install-nix-action@v18
      with: 
        nix_path: nixpkgs=channel:nixos-22.11

    - name: Set known hosts
      run: install -D -m 600 known_hosts/known_hosts ~/.ssh/known_hosts
    
    - name: Deploy
      run: |
        eval "$(ssh-agent)"
        ssh-add - <<< "${{secrets.serversshkey}}"
        cd infra
        nix-build -A config.toplevel gen.nix -I infra=./infra.nix
        nix-env -i libvirt -f '<nixpkgs>'
        bash result/deploy || true
