name: Update courses view
on:
  workflow_dispatch:
    inputs:
      catalog:
        required: true
        type: string
      rev:
        required: true
        type: string
  workflow_call:
    inputs:
      rev:
        required: true
        type: string
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        github_access_token: ${{secrets.GITHUB_TOKEN}}
        extra_nix_config: |
          access-tokens = github.com=${{secrets.PAT}}

    - name: Update
      run: |
        sed -i "s#rev = \"[^\"]*\"#rev = \"${{inputs.rev}}\"#" ./machines/$(jq -r ".\"${{inputs.catalog}}\".machine" <courses.json)/view.nix
        nix run .#updateCoursesView.${{inputs.catalog}}

    - name: Commit
      run: |
        git config user.name lpm-automaton
        git config user.email lpm-automaton@protonmail.com
        git add -u
        git commit -m "Update courses view"
        git push
