name: Update manually

on:
  workflow_dispatch:
    inputs:
      input:
        required: true
        type: string

jobs:
  update:
    uses: ./.github/workflows/update.yml
    with:
      input: ${{inputs.input}}
